{{- if .Values.ontopic.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: ontopic-angular-frontend
spec:
  ports:
  - name: http
    port: 4200
    targetPort: 4200
  selector:
    app: ontopic-angular-frontend
  type: ClusterIP
{{- end }}
