{{- if .Values.ontopic.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: ontopic-process-server
spec:
  ports:
  - name: http
    port: 8666
    targetPort: 8666
  selector:
    app: ontopic-process-server
  type: ClusterIP
{{- end }}
