# use this class to enable aws ebs volumes in an EKS cluster
{{- if and .Values.storage.customAwsClass .Values.storage.className }}
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: {{ .Values.storage.className }}
provisioner: ebs.csi.aws.com
reclaimPolicy: {{ .Values.storage.reclaimPolicy }}
allowVolumeExpansion: true
mountOptions:
  - debug
volumeBindingMode: Immediate
{{- end }}
