{{- $sa := .Values.serviceAccount | default dict }}
{{- if $sa.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ $sa.name | default .Release.Name }}
  labels:
    app: {{ .Release.Name }}
  {{- with $sa.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}