apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.container.name }}
spec:
  ports:
  - name: {{ .Values.service.portName }}
    port: {{ .Values.service.port }}
    targetPort: {{ .Values.service.targetPort }}
  selector:
    app: {{ .Values.container.name }}
  type: {{ .Values.service.type }}
  # this is for HA use-cases
#  sessionAffinity: ClientIP
